Repository edgexfoundry/ci-build-images, pull requests merged in 2020-03, with the labels that each got.

#117 update lftools to latest v0.31.0
  Dockerfile
  Dockerfile.logs-publish
  Jenkinsfile
Labels: geneva, phase 3

#119 Add image for yamllint to use in cd-management
  Dockerfile
  Jenkinsfile
  README.md
Labels: geneva

#121 update lftools to use python3
  Dockerfile
Labels: bug

#122 update alternatives to make python3 default
  Dockerfile
Labels: bug

#123 add fix for urlgrabber python script
  Dockerfile
Labels: bug, geneva

#126 migrate to gradle
  Dockerfile
  Jenkinsfile
  settings.xml
Labels: 2-medium, enhancement, geneva
