Repository edgexfoundry/ci-build-images, pull requests merged in 2020-01, with the labels that each got.

#91 add releaseBranchOverride parameter
  Jenkinsfile
Labels: bug, geneva

#92 add new option to allow custom release branch override
  Jenkinsfile
Labels: bug, geneva

#93 add new option to allow custom release branch override
  Jenkinsfile
Labels: bug, geneva

#94 add new option to allow custom release branch override
  Jenkinsfile
Labels: bug, geneva

#96 add new option to allow custom release branch override
  Jenkinsfile
Labels: bug, geneva

#97 add new option to allow custom release branch override
  Jenkinsfile
Labels: bug, geneva

#98 add new option to allow custom release branch override
  Jenkinsfile
Labels: bug, geneva

#99 add new option to allow custom release branch override
  Jenkinsfile
Labels: bug, geneva

#100 add new option to allow custom release branch override
  Jenkinsfile
Labels: bug, geneva

#101 add new option to allow custom release branch override
  Jenkinsfile
Labels: bug, geneva

#102 add new option to allow custom release branch override
  Jenkinsfile
Labels: bug, geneva

#89 Add golang 1.13 base image
  .golangci.yml
  Dockerfile
  Jenkinsfile
  README.md
  linter-settings.json
Labels: geneva

#90 Add golang 1.13 to README
  README.md
Labels: geneva

#107 add sandbox Jenkinsfile
  Jenkinsfile.sandbox
Labels: enhancement
