Repository edgexfoundry/ci-build-images, pull requests merged in 2022-10, with the labels that each got.

#197 ci: update to golang 1.17.13
  Dockerfile
Labels: enhancement, ci, hacktoberfest-accepted, hacktoberfest

#198 feat: upgrade to Snyk CLI v1.1025.0
  Dockerfile
  Jenkinsfile
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, levski

#196 ci: update to golang 1.18.7
  Dockerfile
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#200 ci: upgrade gradle image from 6.5 to 7.5.1
  Dockerfile
Labels: 2-medium, ci, hacktoberfest-accepted, hacktoberfest
